import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import SidebarHome from "@/components/sidebar/sidebarHome";

const cairo = Cairo({
  subsets: ['arabic'],
})



export const metadata: Metadata = {
  title: "agricode",
  description: "Generated by create next app",
  icons : {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cairo.className}
      >
        <Navbar />
        <main>
          <SidebarHome />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
